version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: whatsapp_wishlist_mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password

  backend:
    build: ./api
    container_name: whatsapp_wishlist_api
    ports:
      - "3001:3001"
    environment:
      MONGO_URI: mongodb://admin:password@mongodb:27017/whatsapp_wishlist?authSource=admin
      PORT: 3001
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    container_name: whatsapp_wishlist_frontend
    ports:
      - "5173:5173"
    environment:
      REACT_APP_API_URL: http://localhost:3001
    depends_on:
      - backend
